using Microsoft.Reporting.WinForms;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace RecursiveHierarchyGroup
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            IEnumerable<Employee> Employees = GetData();
            ReportDataSource datasource = new ReportDataSource("DataSet1", Employees.Where(p=>p.Id<500));
            this.reportViewer1.LocalReport.DataSources.Clear();
            this.reportViewer1.LocalReport.DataSources.Add(datasource);
            this.reportViewer1.RefreshReport();
        }

        private IEnumerable<Employee> GetData()
        {
            return new Employee[]
            {
                new Employee {Id=   339 ,ManagerId= null,   Name="	Stroke/TIA	"},
                new Employee {Id=   367 ,ManagerId= 339,   Name="	Alzheimer's Disease	"},
                new Employee {Id=   368 ,ManagerId= 339,   Name="	Dementia	"},
                new Employee {Id=   369 ,ManagerId= 339,   Name="	Parkinson’s Disease (Paralysis Agitans)	"},

                new Employee {Id=   370 ,ManagerId= 367,   Name="	Neuropathy	"},
                new Employee {Id=   378 ,ManagerId= 367,   Name="	Migraine Headache	"},
                new Employee {Id=   391 ,ManagerId= 367,   Name="	Multiple Sclerosis	"},

                new Employee {Id=   396 ,ManagerId= 368,   Name="	Cerebral Palsy	"},
                new Employee {Id=   397 ,ManagerId= 368,   Name="	Muscular Dystrophy	"},
                new Employee {Id=   398 ,ManagerId= 368,   Name="	Developmental Disorder	"},

                new Employee {Id=   399 ,ManagerId= 369,   Name="	Paralysis	"},
                new Employee {Id=   401 ,ManagerId= 369 ,   Name="	Paraplegia	"},
                new Employee {Id=   406 ,ManagerId= 369 ,   Name="	Quadriplegia	"},

                new Employee {Id=   408 ,ManagerId= 370 ,   Name="	Spina Bifida	"},
                new Employee {Id=   409 ,ManagerId= 370 ,   Name="	Other Disease of Spinal Cord	"},
                new Employee {Id=   494 ,ManagerId= 378,   Name="	Seizure	"},


                new Employee {Id=   507 ,ManagerId= 378,   Name="	Myasthenia Gravis	"},
                new Employee {Id=   508 ,ManagerId= 378,   Name="	Lambert-Eaton Syndrome	"},
                new Employee {Id=   509 ,ManagerId= 391,   Name="	Myelitis	"},
                new Employee {Id=   513 ,ManagerId= 391,   Name="	Other Neurological Disorder	"},
                new Employee {Id=   520 ,ManagerId= 396,   Name="	Heart Failure (Not Due to Hypertensive Heart Disease)	"},
                new Employee {Id=   522 ,ManagerId= 396,   Name="	Coronary Artery Disease	"},
                new Employee {Id=   539 ,ManagerId= 399,   Name="	Abnormal Heart Rhythm	"},
                new Employee {Id=   540 ,ManagerId= 399 ,   Name="	Ventricular Arrhythmia (V-Fib or V-Tach)	"},
                new Employee {Id=   541 ,ManagerId= 539 ,   Name="	Slow Heart Rate	"},
                new Employee {Id=   542 ,ManagerId= 539 ,   Name="	Atrial Fibrillation/Atrial Flutter	"},
                new Employee {Id=   544 ,ManagerId= 401,   Name="	Heart Valve Disease	"},
                new Employee {Id=   547 ,ManagerId= 401,   Name="	Other Cardiac Disease	"},
                new Employee {Id=   554 ,ManagerId= 406,   Name="	COPD/Chronic Obstructive Pulmonary Disorder	"},
                new Employee {Id=   555 ,ManagerId= 406 ,   Name="	Chronic Bronchitis	"},
                new Employee {Id=   556 ,ManagerId= 554 ,   Name="	Emphysema	"},
                new Employee {Id=   557 ,ManagerId= 408,   Name="	Pneumonia	"},
                new Employee {Id=   558 ,ManagerId= 408 ,   Name="	Strep	"},
                new Employee {Id=   559 ,ManagerId= 409 ,   Name="	Staph	"},
                new Employee {Id=   560 ,ManagerId= 409 ,   Name="	H.Flu	"},
                new Employee {Id=   561 ,ManagerId= 494 ,   Name="	Other	"},
                new Employee {Id=   562 ,ManagerId= 494,   Name="	Lung Abscess	"},
                new Employee {Id=   563 ,ManagerId= 507,   Name="	Asthma	"},
                new Employee {Id=   565 ,ManagerId= 507,   Name="	Bronchiectasis	"},
                new Employee {Id=   573 ,ManagerId= 513,   Name="	Other Pulmonary Disease	"},
                new Employee {Id=   600 ,ManagerId= 513,   Name="	Crohn's Disease	"},
                new Employee {Id=   607 ,ManagerId= 520,   Name="	Ulcerative Colitis	"},
                new Employee {Id=   615 ,ManagerId= 520,   Name="	Liver Disease	"},
                new Employee {Id=   629 ,ManagerId= 522,   Name="	Colon Polyps	"},
                new Employee {Id=   634 ,ManagerId= 522,   Name="	Ileus or Obstruction	"},
                new Employee {Id=   635 ,ManagerId= 539,   Name="	Other Gastrointestinal Disease	"},
                new Employee {Id=   667 ,ManagerId= 539,   Name="	Osteoporosis	"},
                new Employee {Id=   668 ,ManagerId= 667 ,   Name="	Bone Fracture due to Osteoporosis?	"},
                new Employee {Id=   789 ,ManagerId= 557,   Name="	Hip Fracture	"},
                new Employee {Id=   790 ,ManagerId= 557,   Name="	Hip Dislocation/Subluxation Hip	"},
                new Employee {Id=   1682 ,ManagerId= 629,   Name="	Other Bone/Joint Infection	"},
                new Employee {Id=   1973 ,ManagerId= 629,   Name="	Polio Osteopathy	"},
                new Employee {Id=   2010 ,ManagerId= 629,   Name="	Malignant Cancer	"},
                new Employee {Id=   2021 ,ManagerId= 2010,   Name="	Breast	"},
                new Employee {Id=   2130 ,ManagerId= 2010,   Name="	Other Cancer	"},
                new Employee {Id=   2138 ,ManagerId= 2130,   Name="	Metastatic Cancer	"},
                new Employee {Id=   2157 ,ManagerId= 2130,   Name="	Lymphoma	"},
                new Employee {Id=   2187 ,ManagerId= 2157    ,Name="	Hodgkin Lymphoma	"},
                new Employee {Id=   2195 ,ManagerId= 790,   Name="	Multiple Myeloma	"},
                new Employee {Id=   2199 ,ManagerId= 790,   Name="	Leukemia	"},
                new Employee {Id=   2237 ,ManagerId= 1973,   Name="	Anemia	"},
                new Employee {Id=   2246 ,ManagerId= 1973,   Name="	Clotting Disorder	"},
                new Employee {Id=   2249 ,ManagerId= 1973,   Name="	Pancytopenia	"},
                new Employee {Id=   2250 ,ManagerId= 2138,   Name="	Neutropenia	"},
                new Employee {Id=   2251 ,ManagerId= 2138,   Name="	Other Blood Disease	"},
                new Employee {Id=   2252 ,ManagerId= 2138,   Name="	Systemic Lupus Erythematosus	"},
                new Employee {Id=   2260 ,ManagerId= null,   Name="	Sarcoidosis	"},
                new Employee {Id=   2261 ,ManagerId= null,   Name="	Polymyalgia Rheumatica	"},
                new Employee {Id=   2269 ,ManagerId= null,   Name="	Other Autoimmune Disease	"},
                new Employee {Id=   2270 ,ManagerId= null,   Name="	Parathyroid Disease	"},
                new Employee {Id=   2271 ,ManagerId= null,   Name="	Thymus Disease	"},
                new Employee {Id=   2272 ,ManagerId= null,   Name="	Pituitary Disease	"},
                new Employee {Id=   2273 ,ManagerId= null,   Name="	Adrenal Disease	"},
                new Employee {Id=   2275 ,ManagerId= null,   Name="	Other Endocrine Disease	"},
                new Employee {Id=   2287 ,ManagerId= null,   Name="	Depression Psychosis (Major Depression)	"},
                new Employee {Id=   2290 ,ManagerId= null,   Name="	Anxiety	"},
                new Employee {Id=   2291 ,ManagerId= null,   Name="	Bipolar Disorder	"},
                new Employee {Id=   2295 ,ManagerId= null,   Name="	Schizophrenia	"},
                new Employee {Id=   2296 ,ManagerId= null,   Name="	Mood Disorder	"},
                new Employee {Id=   2298 ,ManagerId= null,   Name="	Self-Injury or Suicide Attempt	"},
                new Employee {Id=   2303 ,ManagerId= null,   Name="	Other Mental Health Disorder	"},
                new Employee {Id=   2304 ,ManagerId= null,   Name="	Arterial Dissection	"},
                new Employee {Id=   2305 ,ManagerId= 2304    ,Name="	Abdominal Aorta	"},
                new Employee {Id=   2306 ,ManagerId= 2304    ,Name="	Thoracic Aorta	"},
                new Employee {Id=   2307 ,ManagerId= 2304    ,Name="	Thoracoabdominal Aorta	"},
                new Employee {Id=   2309 ,ManagerId= 2304    ,Name="	Other Arterial Dissection	"},
                new Employee {Id=   2310 ,ManagerId= null,   Name="	Arterial Aneurysm	"},
                new Employee {Id=   2311 ,ManagerId= 2310    ,Name="	Thoracic Aorta	"},
                new Employee {Id=   2312 ,ManagerId= 2310    ,Name="	Abdominal Aorta	"},
                new Employee {Id=   2313 ,ManagerId= 2310    ,Name="	Thoracoabdominal Aorta	"},
                new Employee {Id=   2315 ,ManagerId= 2310    ,Name="	Aneurysm of Other Artery	"},
                new Employee {Id=   2321 ,ManagerId= null,   Name="	Peripheral Vascular Disease	"},
                new Employee {Id=   2322 ,ManagerId= null,   Name="	Embolism and Thrombosis (Arterial)	"},
                new Employee {Id=   2323 ,ManagerId= 2322    ,Name="	Aorta	"},
                new Employee {Id=   2324 ,ManagerId= 2322    ,Name="	Artery of the Upper Extremity	"},
                new Employee {Id=   2325 ,ManagerId= 2322    ,Name="	Artery of the Lower Extremity	"},
                new Employee {Id=   2326 ,ManagerId= 2322    ,Name="	Other Artery	"},
                new Employee {Id=   2328 ,ManagerId= null,   Name="	Other Arterial Disease	"},
                new Employee {Id=   2329 ,ManagerId= null,   Name="	Phlebitis and Thrombophlebitis	"},
                new Employee {Id=   2336 ,ManagerId= null,   Name="	Chronic Venous Embolism/Thrombosis (DVT)	"},
                new Employee {Id=   2337 ,ManagerId= 2336    ,Name="	Unspecified Lower Extremity	"},
                new Employee {Id=   2372 ,ManagerId= 2336    ,Name="	Upper Extremity	"},
                new Employee {Id=   2387 ,ManagerId= 2336    ,Name="	Internal Jugular Vein	"},
                new Employee {Id=   2392 ,ManagerId= 2336    ,Name="	Other Vein	"},
                new Employee {Id=   3256 ,ManagerId= null,   Name="	Glaucoma	"},
                new Employee {Id=   3258 ,ManagerId= null,   Name="	Diabetes	"},
                new Employee {Id=   3259 ,ManagerId= null,   Name="	Is your Diabetes regularly treated with insulin injection (needle) and/or an insulin pump?	"},
                new Employee {Id=   3260 ,ManagerId= null,   Name="	Is your Blood Sugar under control? (Is your blood sugar consistently below 100 mg/dl?)	"},
                new Employee {Id=   3261 ,ManagerId= null,   Name="	Have you had any complications or ill effects from your Diabetes? (Such as Kidney Failure, Circulatory Problems, Ulcers, Eye Problems, Neuropathy, Other)	"},
                new Employee {Id=   3262 ,ManagerId= null,   Name="	Kidney Disease Due to DM	"},
                new Employee {Id=   3263 ,ManagerId= null,   Name="	Vascular/Angiopathy (Circulatory)/Ulceration as a Result of DM	"},
                new Employee {Id=   3264 ,ManagerId= null,   Name="	Eye Complication of DM	"},
                new Employee {Id=   3265 ,ManagerId= null,   Name="	Nerve/Neuropathy/Pain Due to DM	"},
                new Employee {Id=   3266 ,ManagerId= null,   Name="	Joint Problems Due to DM	"},
                new Employee {Id=   3267 ,ManagerId= null,   Name="	Skin Problems Due to DM	"},
                new Employee {Id=   3268 ,ManagerId= null,   Name="	Other/Unknown Complication of DM	"},
                new Employee {Id=   3270 ,ManagerId= null,   Name="	Kidney Disease	"},
                new Employee {Id=   3271 ,ManagerId= null,   Name="	Do you go to Dialysis?	"},
                new Employee {Id=   3272 ,ManagerId= null,   Name="	Do you have a Vascular Graft (A/V Fistula) for Dialysis?	"},
                new Employee {Id=   3273 ,ManagerId= null,   Name="	HIV/AIDS/Opportunistic Infection with or without HIV/AIDS	"},
                new Employee {Id=   3274 ,ManagerId= null,   Name="	HIV/AIDS with Opportunistic Infection	"},
                new Employee {Id=   3275 ,ManagerId= null,   Name="	Skin Ulcer (Such as Bed Sores or Pressure Ulcerations of Skin)	"},
                new Employee {Id=   3276 ,ManagerId= null,   Name="	Skin Disease	"},
                new Employee {Id=   3277 ,ManagerId= null,   Name="	Do you have any of the following Neurological (Nerve and Brain) or Developmental Disorders?	"},
                new Employee {Id=   3279 ,ManagerId= null,   Name="	Do you still have any changes in your movement as a result of your stroke?	"},
                new Employee {Id=   3280 ,ManagerId= null,   Name="	Stroke Movement Side of Body Affected:	"},
                new Employee {Id=   3281 ,ManagerId= null,   Name="	Unknown Cause Paralysis	"},
                new Employee {Id=   3282 ,ManagerId= null,   Name="	Brain Injury	"},
                new Employee {Id=   3283 ,ManagerId= null,   Name="	No Skull Fracture	"},
                new Employee {Id=   3284 ,ManagerId= null,   Name="	Skull Fracture	"},
                new Employee {Id=   3285 ,ManagerId= null,   Name="	Eye Orbit Fracture	"},
                new Employee {Id=   3286 ,ManagerId= null,   Name="	Fracture of Mandible (Jaw)	"},
                new Employee {Id=   3287 ,ManagerId= null,   Name="	Other Skull Fracture	"},
                new Employee {Id=   3288 ,ManagerId= null,   Name="	Brain Bleed	"},
                new Employee {Id=   3289 ,ManagerId= null,   Name="	Intracerebral Bleed	"},
                new Employee {Id=   3290 ,ManagerId= null,   Name="	Subdural Bleed	"},
                new Employee {Id=   3291 ,ManagerId= null,   Name="	Intracranial Bleed	"},
                new Employee {Id=   3292 ,ManagerId= null,   Name="	Other Head Bleed	"},
                new Employee {Id=   3293 ,ManagerId= null,   Name="	Unknown Head Bleed	"},
                new Employee {Id=   3294 ,ManagerId= null,   Name="	Was your movement affected as a result of a brain/head bleed?	"},
                new Employee {Id=   3295 ,ManagerId= null,   Name="	Brain Bleed Side of Body Affected:	"},
                new Employee {Id=   3297 ,ManagerId= null,   Name="	Diabetic Neuropathy	"},
                new Employee {Id=   3298 ,ManagerId= null,   Name="	Huntington's Disease	"},
                new Employee {Id=   3299 ,ManagerId= null,   Name="	Cerebral Disease	"},
                new Employee {Id=   3300 ,ManagerId= null,   Name="	Cauda Equina	"},
                new Employee {Id=   3301 ,ManagerId= null,   Name="	Unknown Neurological Problems	"},
                new Employee {Id=   3302 ,ManagerId= null,   Name="	High Blood Pressure	"},
                new Employee {Id=   3303 ,ManagerId= null,   Name="	Have you been diagnosed with Heart Failure as a result of your High Blood Pressure?	"},
                new Employee {Id=   3304 ,ManagerId= null,   Name="	Do you have Kidney Disease/Kidney Failure as a result of your High Blood Pressure?	"},
                new Employee {Id=   3306 ,ManagerId= null,   Name="	High Cholesterol	"},
                new Employee {Id=   3307 ,ManagerId= null,   Name="	Do you have any of the following Heart Problems?	"},
                new Employee {Id=   3308 ,ManagerId= null,   Name="	Heart Attack	"},
                new Employee {Id=   3309 ,ManagerId= null,   Name="	Was your heart attack within the last 8 weeks?	"},
                new Employee {Id=   3312 ,ManagerId= null,   Name="	Do you have Mitral Heart Valve Disease (Mitral Valve Prolapse, Regurgitation or "},
                new Employee {Id=   3313 ,ManagerId= null,   Name="	Angina/Chest Pain	"},
                new Employee {Id=   3314 ,ManagerId= null,   Name="	Unknown Abnormal Heart Rhythm	"},
                new Employee {Id=   3315 ,ManagerId= null,   Name="	Do you currently take a blood thinner (Such as Coumadin, Warfarin, etc.)?	"},
                new Employee {Id=   3317 ,ManagerId= null,   Name="	Unknown Heart Problems	"},
                new Employee {Id=   3318 ,ManagerId= null,   Name="	Do you have any of the following Lung Problems?	"},
                new Employee {Id=   3320 ,ManagerId= null,   Name="	Other COPD	"},
                new Employee {Id=   3321 ,ManagerId= null,   Name="	Unknown COPD	"},
                new Employee {Id=   3322 ,ManagerId= null,   Name="	Unknown Pneumonia	"},
                new Employee {Id=   3324 ,ManagerId= null,   Name="	Interstitial Pneumonitis/Pulmonary Fibrosis	"},
                new Employee {Id=   3325 ,ManagerId= null,   Name="	Asbestosis	"},
                new Employee {Id=   3326 ,ManagerId= null,   Name="	Inhaled Fumes	"},
                new Employee {Id=   3327 ,ManagerId= null,   Name="	Silica	"},
                new Employee {Id=   3328 ,ManagerId= null,   Name="	Coal Worker	"},
                new Employee {Id=   3330 ,ManagerId= null,   Name="	Unknown Lung Disease	"},
                new Employee {Id=   3331 ,ManagerId= null,   Name="	Do you have any of the following Gastrointestinal Problems?	"},
                new Employee {Id=   3332 ,ManagerId= null,   Name="	Intestinal Perforation	"},
                new Employee {Id=   3333 ,ManagerId= null,   Name="	Stomach Perforation	"},
                new Employee {Id=   3334 ,ManagerId= null,   Name="	Peritonitis (Infection in Abdominal Cavity)	"},
                new Employee {Id=   3335 ,ManagerId= null,   Name="	Abscess	"},
                new Employee {Id=   3336 ,ManagerId= null,   Name="	Hepatitis	"},
                new Employee {Id=   3337 ,ManagerId= null,   Name="	Cirrhosis	"},
                new Employee {Id=   3338 ,ManagerId= null,   Name="	Pancreatitis	"},
                new Employee {Id=   3339 ,ManagerId= null,   Name="	Esophageal Varices	"},
                new Employee {Id=   3340 ,ManagerId= null,   Name="	Unknown GI Problems	"},
                new Employee {Id=   3341 ,ManagerId= null,   Name="	Do you have any of the following Bone Problems?	"},
                new Employee {Id=   3343 ,ManagerId= null,   Name="	Broken Neck	"},
                new Employee {Id=   3344 ,ManagerId= null,   Name="	Broken Back	"},
                new Employee {Id=   3345 ,ManagerId= null,   Name="	Non-Healing Bone (Avascular Necrosis)	"},
                new Employee {Id=   3348 ,ManagerId= null,   Name="	Other Bone Problem	"},
                new Employee {Id=   3349 ,ManagerId= null,   Name="	Unknown Bone Problems	"},
                new Employee {Id=   3350 ,ManagerId= null,   Name="	Do you have any of the following Joint Problems?	"},
                new Employee {Id=   3351 ,ManagerId= null,   Name="	Joint Problem Shoulder	"},
                new Employee {Id=   3352 ,ManagerId= null,   Name="	Joint Problem Upper Arm	"},
                new Employee {Id=   3353 ,ManagerId= null,   Name="	Joint Problem Forearm	"},
                new Employee {Id=   3354 ,ManagerId= null,   Name="	Joint Problem Hand	"},
                new Employee {Id=   3355 ,ManagerId= null,   Name="	Joint Problem Pelvis	"},
                new Employee {Id=   3356 ,ManagerId= null,   Name="	Joint Problem Leg	"},
                new Employee {Id=   3357 ,ManagerId= null,   Name="	Joint Problem Ankle	"},
                new Employee {Id=   3358 ,ManagerId= null,   Name="	Joint Problem Multiple Joints	"},
                new Employee {Id=   3359 ,ManagerId= null,   Name="	Joint Problem Unspecified	"},
                new Employee {Id=   3360 ,ManagerId= null,   Name="	Joint Problem Unknown	"},
                new Employee {Id=   3361 ,ManagerId= null,   Name="	Do you use anti-inflammatory or analgesic over-the-counter (OTC) medications for symptom relief?	"},
                new Employee {Id=   3362 ,ManagerId= null,   Name="	Are you currently being treated, treated in the past year, or refused treatment for any of the following cancers:	"},
                new Employee {Id=   3363 ,ManagerId= null,   Name="	Malignant Lung Cancer	"},
                new Employee {Id=   3364 ,ManagerId= null,   Name="	Malignant Colon/Rectum/Anus Cancer	"},
                new Employee {Id=   3365 ,ManagerId= null,   Name="	Malignant Thyroid Gland Cancer	"},
                new Employee {Id=   3366 ,ManagerId= null,   Name="	Malignant Bone Cancer	"},
                new Employee {Id=   3367 ,ManagerId= null,   Name="	Bone Fracture due to Cancer	"},
                new Employee {Id=   3368 ,ManagerId= null,   Name="	Malignant Kidney Cancer	"},
                new Employee {Id=   3369 ,ManagerId= null,   Name="	Malignant Bladder Cancer	"},
                new Employee {Id=   3370 ,ManagerId= null,   Name="	Malignant Skin (Melanoma) Cancer	"},
                new Employee {Id=   3371 ,ManagerId= null,   Name="	Malignant Liver Cancer	"},
                new Employee {Id=   3372 ,ManagerId= null,   Name="	Malignant Pancreas Cancer	"},
                new Employee {Id=   3373 ,ManagerId= null,   Name="	Malignant Brain/Spinal Cord Cancer	"},
                new Employee {Id=   3374 ,ManagerId= null,   Name="	Malignant Esophagus Cancer	"},
                new Employee {Id=   3375 ,ManagerId= null,   Name="	Malignant Stomach Cancer	"},
                new Employee {Id=   3376 ,ManagerId= null,   Name="	Malignant Small Bowel/Intestines Cancer	"},
                new Employee {Id=   3377 ,ManagerId= null,   Name="	Malignant Gall Bladder Cancer	"},
                new Employee {Id=   3378 ,ManagerId= null,   Name="	Cancer of Lining of Inner Abdominal Wall or Peritoneum	"},
                new Employee {Id=   3379 ,ManagerId= null,   Name="	Malignant Appendix Cancer	"},
                new Employee {Id=   3380 ,ManagerId= null,   Name="	Malignant Adrenal Gland Cancer	"},
                new Employee {Id=   3381 ,ManagerId= null,   Name="	Malignant Spleen Cancer	"},
                new Employee {Id=   3382 ,ManagerId= null,   Name="	Malignant Soft Tissue Cancer	"},
                new Employee {Id=   3383 ,ManagerId= null,   Name="	Malignant Thorax/Mediastinum (behind breast bone) Cancer	"},
                new Employee {Id=   3384 ,ManagerId= null,   Name="	Malignant Nerve Cancer	"},
                new Employee {Id=   3385 ,ManagerId= null,   Name="	Malignant Heart Cancer	"},
                new Employee {Id=   3386 ,ManagerId= null,   Name="	Malignant Cervix/Uterus/Vagina Cancer	"},
                new Employee {Id=   3387 ,ManagerId= null,   Name="	Malignant Ovary/Fallopian Tube/Adnexa Cancer	"},
                new Employee {Id=   3388 ,ManagerId= null,   Name="	Malignant Prostate Cancer	"},
                new Employee {Id=   3389 ,ManagerId= null,   Name="	Malignant Male Genitalia Cancer	"},
                new Employee {Id=   3390 ,ManagerId= null,   Name="	Malignant Male Ureter/Urethra Cancer	"},
                new Employee {Id=   3391 ,ManagerId= null,   Name="	Malignant Parathyroid Gland Cancer	"},
                new Employee {Id=   3392 ,ManagerId= null,   Name="	Malignant Thymus Gland Cancer	"},
                new Employee {Id=   3393 ,ManagerId= null,   Name="	Malignant Head and Neck (Larynx, Sinus, Tongue, Parotid Gland, Mouth,Palate, Epiglottis, Submandibular, Eye, Salivary, Nasopharynx, Oropharynx, Hypopharynx) Cancer	"},
                new Employee {Id=   3394 ,ManagerId= null,   Name="	Malignant Eye Cancer	"},
                new Employee {Id=   3395 ,ManagerId= null,   Name="	Malignant Trachea Cancer	"},
                new Employee {Id=   3396 ,ManagerId= null,   Name="	Lymph Nodes Cancer	"},
                new Employee {Id=   3397 ,ManagerId= null,   Name="	Unknown Malignant Cancer	"},
                new Employee {Id=   3410 ,ManagerId= null,   Name="	Organ Transplant	"},
                new Employee {Id=   3411 ,ManagerId= null,   Name="	Soft Tissue Cancer (Muscle, Fat)	"},
                new Employee {Id=   3412 ,ManagerId= null,   Name="	Carcinoid	"},
                new Employee {Id=   3414 ,ManagerId= null,   Name="	Burkitt Tumor	"},
                new Employee {Id=   3415 ,ManagerId= null,   Name="	Other Cancer	"},
                new Employee {Id=   3416 ,ManagerId= null,   Name="	Unknown Cancer	"},
                new Employee {Id=   3417 ,ManagerId= null,   Name="	Do you have any of the following Blood Disorders?	"},
                new Employee {Id=   3418 ,ManagerId= null,   Name="	Sickle Cell Anemia	"},
                new Employee {Id=   3419 ,ManagerId= null,   Name="	Thalassemia	"},
                new Employee {Id=   3420 ,ManagerId= null,   Name="	Aplastic Anemia	"},
                new Employee {Id=   3421 ,ManagerId= null,   Name="	Hemolytic Anemia	"},
                new Employee {Id=   3422 ,ManagerId= null,   Name="	Von Willebrand's	"},
                new Employee {Id=   3423 ,ManagerId= null,   Name="	Unknown Blood Disorder	"},
                new Employee {Id=   3424 ,ManagerId= null,   Name="	Do you have any of the following Immune/Autoimmune Disorders?	"},
                new Employee {Id=   3425 ,ManagerId= null,   Name="	Unknown Autoimmune Disorders	"},
                new Employee {Id=   3426 ,ManagerId= null,   Name="	Do you have any of the following Endocrine Disorders?	"},
                new Employee {Id=   3427 ,ManagerId= null,   Name="	Unknown Endocrine Disorder	"},
                new Employee {Id=   3428 ,ManagerId= null,   Name="	Do you have any of the following Metabolic Disorders?	"},
                new Employee {Id=   3429 ,ManagerId= null,   Name="	Phenylketonuria (PKU)	"},
                new Employee {Id=   3430 ,ManagerId= null,   Name="	Amino-Acid Disorder	"},
                new Employee {Id=   3431 ,ManagerId= null,   Name="	Cystic Fibrosis	"},
                new Employee {Id=   3432 ,ManagerId= null,   Name="	Other Metabolic Disorder	"},
                new Employee {Id=   3433 ,ManagerId= null,   Name="	Unknown Metabolic Disorder	"},
                new Employee {Id=   3434 ,ManagerId= null,   Name="	Do you have any of the following Psychological Disorders?	"},
                new Employee {Id=   3435 ,ManagerId= null,   Name="	Depression Psychosis	"},
                new Employee {Id=   3436 ,ManagerId= null,   Name="	Schizophrenia	"},
                new Employee {Id=   3437 ,ManagerId= null,   Name="	Delusion	"},
                new Employee {Id=   3438 ,ManagerId= null,   Name="	Unknown Psychological Disorder	"},
                new Employee {Id=   3439 ,ManagerId= null,   Name="	Do you have any of the following Vascular (Artery, Vein) Disorders?	"},
                new Employee {Id=   3440 ,ManagerId= null,   Name="	Carotid Artery Dissection	"},
                new Employee {Id=   3441 ,ManagerId= null,   Name="	Aneurysm Arm	"},
                new Employee {Id=   3442 ,ManagerId= null,   Name="	Aneurysm Leg	"},
                new Employee {Id=   3443 ,ManagerId= null,   Name="	Aneurysm Neck	"},
                new Employee {Id=   3444 ,ManagerId= null,   Name="	Aneurysm Renal	"},
                new Employee {Id=   3445 ,ManagerId= null,   Name="	Aneurysm Iliac	"},
                new Employee {Id=   3446 ,ManagerId= null,   Name="	Aneurysm Spleen	"},
                new Employee {Id=   3447 ,ManagerId= null,   Name="	Other Blood Clots	"},
                new Employee {Id=   3448 ,ManagerId= null,   Name="	Phlebitis Arm	"},
                new Employee {Id=   3449 ,ManagerId= null,   Name="	Phlebitis Leg	"},
                new Employee {Id=   3450 ,ManagerId= null,   Name="	Artery Blockage Arm	"},
                new Employee {Id=   3451 ,ManagerId= null,   Name="	Artery Blockage Leg	"},
                new Employee {Id=   3452 ,ManagerId= null,   Name="	Artery Blockage Bypass Graft Surgery	"},
                new Employee {Id=   3453 ,ManagerId= null,   Name="	Artery Blockage Other (Intestinal, Renal, Aorta)	"},
                new Employee {Id=   3454 ,ManagerId= null,   Name="	Artery Clot Renal	"},
                new Employee {Id=   3455 ,ManagerId= null,   Name="	Artery Clot Vena Cava	"},
                new Employee {Id=   3456 ,ManagerId= null,   Name="	Ruptured Aneurysm	"},
                new Employee {Id=   3457 ,ManagerId= null,   Name="	Ruptured Aneurysm Aorta	"},
                new Employee {Id=   3458 ,ManagerId= null,   Name="	Ruptured Aneurysm Chest	"},
                new Employee {Id=   3459 ,ManagerId= null,   Name="	Ruptured Aneurysm Both Aorta and Chest	"},
                new Employee {Id=   3460 ,ManagerId= null,   Name="	Varicose Veins	"},
                new Employee {Id=   3461 ,ManagerId= null,   Name="	Varicose Veins Arm	"},
                new Employee {Id=   3462 ,ManagerId= null,   Name="	Varicose Veins Leg	"},
                new Employee {Id=   3463 ,ManagerId= null,   Name="	Blood Clot in Lung/Pulmonary Embolus	"},
                new Employee {Id=   3464 ,ManagerId= null,   Name="	Gangrene	"},
                new Employee {Id=   3465 ,ManagerId= null,   Name="	Skin Ulcers	"},
                new Employee {Id=   3466 ,ManagerId= null,   Name="	Arteritis	"},
                new Employee {Id=   3469 ,ManagerId= null,   Name="	Unknown Vascular Disease	"},
                new Employee {Id=   3482 ,ManagerId= null,   Name="	Heart Surgery/Procedure (Such as Bypass Surgery, Valve Surgery, Stent)	"},
                new Employee {Id=   3483 ,ManagerId= null,   Name="	Heart Valve Surgery	"},
                new Employee {Id=   3484 ,ManagerId= null,   Name="	Heart Bypass Surgery	"},
                new Employee {Id=   3485 ,ManagerId= null,   Name="	Heart Procedure - Stent or Angioplasty	"},
                new Employee {Id=   3486 ,ManagerId= null,   Name="	Heart - Pacemaker or Defibrillator	"},
                new Employee {Id=   3487 ,ManagerId= null,   Name="	Implanted Device (Such as Limb Prosthesis, Pacemaker, Defibrillator, Insulin Pump, Joint Replacement, Breast Implant, Vascular Graft)	"},
                new Employee {Id=   3495 ,ManagerId= null,   Name="	Have you had any complications or problems with your implanted device within the last year?	"},
                new Employee {Id=   3496 ,ManagerId= null,   Name="	Complication from Heart - Pacemaker or Defibrillator	"},
                new Employee {Id=   3497 ,ManagerId= null,   Name="	Complication from Orthopedic - Joint Replacement such as Hip, Shoulder, Knee	"},
                new Employee {Id=   3498 ,ManagerId= null,   Name="	Complication from Skin Grafting	"},
                new Employee {Id=   3499 ,ManagerId= null,   Name="	Complication from Insulin Pump Implantation	"},
                new Employee {Id=   3500 ,ManagerId= null,   Name="	Complication from Breast Implants	"},
                new Employee {Id=   3501 ,ManagerId= null,   Name="	Complication from Genitourinary - Indwelling Catheter, Penile Implant, Urethral Catheter	"},
                new Employee {Id=   3502 ,ManagerId= null,   Name="	Complication from Vascular Graft	"},
                new Employee {Id=   3503 ,ManagerId= null,   Name="	Complication from Eye Prosthesis	"},
                new Employee {Id=   3504 ,ManagerId= null,   Name="	Other Device/Surgical Wound/System/Bleeding Complications	"},
                new Employee {Id=   3505 ,ManagerId= null,   Name="	Have you been hospitalized or treated in the Emergency Room in the past calendar year (1/1 of current year)?	"},
                new Employee {Id=   3506 ,ManagerId= null,   Name="	Were you admitted to the hospital with heart failure?	"},
                new Employee {Id=   3507 ,ManagerId= null,   Name="	Tracheostomy (Hole in Windpipe)	"},
                new Employee {Id=   3508 ,ManagerId= null,   Name="	Did you have any complications or problems from your tracheostomy?	"},
                new Employee {Id=   3509 ,ManagerId= null,   Name="	Infection from tracheostomy	"},
                new Employee {Id=   3510 ,ManagerId= null,   Name="	Mechanical complication of Tracheostomy	"},
                new Employee {Id=   3511 ,ManagerId= null,   Name="	Other Complication from Tracheostomy	"},
                new Employee {Id=   3512 ,ManagerId= null,   Name="	Unknown Complication from Tracheostomy	"},
                new Employee {Id=   3513 ,ManagerId= null,   Name="	Ostomies (opening in skin to stomach, bowel, intestines, urinary tract, or wearing a bag)	"},
                new Employee {Id=   3514 ,ManagerId= null,   Name="	Gastrostomy (Stomach)	"},
                new Employee {Id=   3515 ,ManagerId= null,   Name="	Ileostomy (Small Bowel)	"},
                new Employee {Id=   3516 ,ManagerId= null,   Name="	Colostomy (Colon)	"},
                new Employee {Id=   3517 ,ManagerId= null,   Name="	Cystostomy (Bladder)/Urinostomy	"},
                new Employee {Id=   3518 ,ManagerId= null,   Name="	Other Ostomy	"},
                new Employee {Id=   3519 ,ManagerId= null,   Name="	Unknown Ostomy	"},
                new Employee {Id=   3520 ,ManagerId= null,   Name="	Complication of Ostomies (Infection, Mechanical Complication)	"},
                new Employee {Id=   3521 ,ManagerId= null,   Name="	Organ Transplant	"},
                new Employee {Id=   3522 ,ManagerId= null,   Name="	Heart Transplant	"},
                new Employee {Id=   3523 ,ManagerId= null,   Name="	Lung Transplant	"},
                new Employee {Id=   3524 ,ManagerId= null,   Name="	Liver Transplant	"},
                new Employee {Id=   3526 ,ManagerId= null,   Name="	Bone Marrow Transplant	"},
                new Employee {Id=   3527 ,ManagerId= null,   Name="	Pancreas Transplant	"},
                new Employee {Id=   3528 ,ManagerId= null,   Name="	Intestines Transplant	"},
                new Employee {Id=   3529 ,ManagerId= null,   Name="	Stem Cell Transplant	"},
                new Employee {Id=   3530 ,ManagerId= null,   Name="	Mechanical Heart Device such as LVAD	"},
                new Employee {Id=   3531 ,ManagerId= null,   Name="	Transplant Rejection	"},
                new Employee {Id=   3532 ,ManagerId= null,   Name="	Other Transplant	"},
                new Employee {Id=   3533 ,ManagerId= null,   Name="	Amputation (Severed from an accident, or surgically amputated)	"},
                new Employee {Id=   3534 ,ManagerId= null,   Name="	Amputation Toe	"},
                new Employee {Id=   3535 ,ManagerId= null,   Name="	Amputation Foot/Ankle	"},
                new Employee {Id=   3536 ,ManagerId= null,   Name="	Amputation Leg - Below Knee	"},
                new Employee {Id=   3537 ,ManagerId= null,   Name="	Amputation Leg - Above Knee	"},
                new Employee {Id=   3538 ,ManagerId= null,   Name="	Amputation At Hip	"},
                new Employee {Id=   3539 ,ManagerId= null,   Name="	Amputation Arm/Hand/Finger	"},
                new Employee {Id=   3540 ,ManagerId= null,   Name="	Do you have an Artificial Leg or amputated extremity that was reattached?	"},
                new Employee {Id=   3541 ,ManagerId= null,   Name="	Have you had any Complications or any late effects from your Amputation?	"},
                new Employee {Id=   3547 ,ManagerId= null,   Name="	Have you had a third-degree burn since 1/1 of current year or late effects of third-degree burn that are present as of 1/1 of current year?	"},
                new Employee {Id=   3552 ,ManagerId= null,   Name="	Did you undergo cardiac rehabilitation after your heart surgery?	"},
                new Employee {Id=   3553 ,ManagerId= null,   Name="	Did you undergo cardiac rehabilitation after your heart angioplasty/stenting?	"},

            };
        }
    }
}
